---
title: "Visual Analytics Module 12 - Graphing a Network"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, echo=FALSE, include=FALSE}
packages <- c('igraph', 'readr')
for(p in packages){
  if(!require(p,character.only = TRUE)) install.packages(p, dependencies = TRUE)
  suppressMessages(library(p,character.only = TRUE))
}
```

```{r tkplot, echo=TRUE, include=FALSE}
g1 = graph_from_literal(a-b-c-d-e-f, a-g-h-b, h:e:f:b)
#tkplot(g1,edge.curved=TRUE)
```

For this assignment, I will be using datasets containing the relationships found in media. I will first import the data into R and then create a matrix in order to plot the data.

```{r network, echo=TRUE, comment=NA, message=FALSE}
#import data

net_nodes = read_csv("https://www.dropbox.com/s/ieaoo7efx87etyk/Dataset1-Media-Example-NODES.csv?dl=1")
net_edges = read.csv("https://www.dropbox.com/s/s4mli5l6j30gc5n/Dataset1-Media-Example-EDGES.csv?dl=1")
#Create an adjacency matrix for net_edges
net_edges_mat = as.matrix(net_edges)
```

```{r networkgraph, echo=TRUE, include=FALSE}
netgraph1 = graph_from_data_frame(d=net_edges, vertices=net_nodes, directed=TRUE) 

#netgraph1_with_loops = tkplot(netgraph1, edge.curved=TRUE)
#With or Without loops
netgraph1_wo_loops = simplify(netgraph1, remove.multiple = F, remove.loops = T) 
#tkplot(netgraph1_wo_loops)
```

```{r graph paramaters, echo=TRUE}
p1 = plot(netgraph1_wo_loops, main = "Time Series Plot (Media)", frame = TRUE, edge.arrow.size=.5, vertex.color = "salmon", vertex.label=net_nodes$media, vertex.label.color="black", vertex.size = 7, edge.curved = .5, edge.width=2, shape='sphere')

tkplot(netgraph1_wo_loops, main = "Network Graph Ex", frame = TRUE, edge.arrow.size=.5, vertex.color = "salmon", vertex.label=net_nodes$media, vertex.label.color="black", vertex.size = 7, vertex.label.family = "Times", edge.curved = .5,)
#edge.curved range is 0-1, TRUE sets to .5
```

